# Change these first
owner: Heywaht # Your GitHub organization or username, where this repository lives
repo: osczstatus # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
  - name: IPv6 test
    url: forwardemail.net
    port: 80
    check: "tcp-ping"
    ipv6: true

status-website:
i18n:
  activeIncidents: Aktive Vorfälle
  allSystemsOperational: Alle Systeme laufen störungsfrei.
  incidentReport: "Vorfall #$NUMBER Report →"
  activeIncidentSummary: Eröffnet am $DATE mit $POSTS Beiträgen
  incidentTitle: Vorfall $NUMBER Details
  incidentDetails: Vorfall Details
  incidentFixed: repariert
  incidentOngoing: andauernd
  incidentOpenedAt: eröffnet am
  incidentClosedAt: Geschlossen am
  incidentSubscribe: Updates abonnieren
  incidentViewOnGitHub: Auf GitHub anschauen
  incidentCommentSummary: Veröffentlicht am $DATE von $AUTHOR
  incidentBack: ← Zurück zu allen Vorfällen
  pastIncidents: Vergangene Vorfälle
  pastIncidentsResolved: Gelöst in $MINUTES Minuten mit $POSTS posts
  liveStatus: Live Status
  overallUptime: "Gesamte Verfügbarkeit: $UPTIME"
  overallUptimeTitle: Gesamte Verfügbarkeit
  averageResponseTime: "Durchschnittliche Antwortzeit: $TIMEms"
  averageResponseTimeTitle: Durchschnittliche Antwortzeit
  sevelDayResponseTime: 7-Tage Antwortzeit
  responseTimeMs: Antwortzeit (ms)
  up: verfügbar
  down: nicht verfügbar
  degraded: Service degradiert
  ms: ms
  loading: am laden
  navGitHub: GitHub
  footer: Für Alle statt für Wenige
  rateLimitExceededTitle: Ratengrenze überschritten
  rateLimitExceededIntro: Sie haben die Ratengrenze überschritten (Request/h). Sie müssen nun warten, bis sie diese Seite erneut besuchen dürfen. Alternativ fügen Sie ein GitHub Personal Access Token hinzu, um diese Seite zu besuchen.
  rateLimitExceededWhatDoesErrorMean: Was bedeutet dieser Fehler?
  rateLimitExceededErrorMeaning: Diese Webseite verwendet die GitHub API um auf Echtzeitdaten über Ihre Webseite zuzugreifen. Standardmässig erlaubt Github 60 Anfragen pro Minute, was Sie nun erreicht haben.
  rateLimitExceededErrorHowCanFix: Wie kann ich es lösen?
  rateLimitExceededErrorFix: Sie können eine Stunde warten oder Sie fügen ein GitHub Personal Access Token hinzu, das Ihnen 5'000 zusätzliche Anfragen pro Stunde ermöglicht.
  rateLimitExceededGeneratePAT: Lernen Sie mehr wie man ein persönliches Access Token generiert.
  rateLimitExceededHasSet: Sie haben ein persönliches Access Token gesetzt.
  rateLimitExceededRemoveToken: Token entfernen
  rateLimitExceededGitHubPAT: GitHub Personal Access Token
  rateLimitExceededCopyPastePAT: Ihr Token kopieren und einfügen
  rateLimitExceededSaveToken: Token speichern
  errorTitle: Ein Fehler ist aufgetreten
  errorIntro: Ein Fehler ist aufgetreten beim Versuch, die letzten Status-Details abzurufen.
  errorText: Sie können es in einem Moment erneut veruchen.
  errorHome: Gehen Sie zur Homepage
  pastScheduledMaintenance: Vergangene geplante Wartungen
  scheduledMaintenance: Geplante Wartungen
  scheduledMaintenanceSummaryStarted: Gestartet am $DATE für $DURATION Minuten
  scheduledMaintenanceSummaryStarts: Startet am $DATE für $DURATION Minuten
  startedAt: Gestartet am
  startsAt: Startet am
  duration: Dauer
  durationMin: $DURATION Minuten
  incidentCompleted: Abgeschlossen
  incidentScheduled: Geplant
  url: "URL"
  status: "Status"
  history: "Geschichte"
  responseTime: "Antwortzeit"
  responseTimeGraphAlt: "Antwortzeit Grafik"
  responseTimeDay: "24-Stunden Antwortzeit"
  responseTimeWeek: "7-Tage Antwortzeit"
  responseTimeMonth: "30-Tage Antwortzeit"
  responseTimeYear: "1-Jahr Antwortzeit"
  uptime: "Gesamtverfügbarkeit"
  uptimeDay: "24-Stunden Verfügbarkeit"
  uptimeWeek: "7-Tage Verfügbarkeit"
  uptimeMonth: "30-Tage Verfügbarkeit"
  uptimeYear: "1-Jahres Verfügbarkeit"
  liveStatusHtmlComment: "<!--live status-->"
  degradedPerformance: "🟨 Leistung degradiert"
  completeOutage: "🟥 Kompletter Ausfall"
  partialOutage: "🟧 Teilausfall"
  theme: light
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /osczstatus # where "repo" is your repository name
  # baseUrl: /your-repo-name
  logoUrl: https://oscz-freiberg.de/wp-content/webp-express/webp-images/uploads/2023/10/logo-ohne-background.png.webp
  favicon: https://oscz-freiberg.de/wp-content/uploads/2023/09/csm_HAUPTLOGO_OSCZ_bunt_e1dda8efcb_2-transformed-1-150x150.png
  name: InFra-OsCZ
  introTitle: "**InFra-OsCZ**: Status-Meldungen, Updates und Hinweise zu den Online-Diensten der Bildungseinrichtung"
  introMessage: Auf dieser Seite sehen Sie in Echtzeit, welche Dienste der Oberschule Online verfügbar sind. Bei Problemen werden Sie hier zuerst informiert. Mehr auf [der Schulwebsite erklärt](https://oscz-freiberg.de/statusinfra).
  navbar:
    - title: Status
      href: /
    - title: Kontakt
      href: mailto:kontakt@oscz-freiberg.de
