# Change these first
owner: Heywaht # Your GitHub organization or username, where this repository lives
repo: osczstatus # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
  - name: IPv6 test
    url: forwardemail.net
    port: 80
    check: "tcp-ping"
    ipv6: true

status-website:
  theme: light
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /osczstatus # where "repo" is your repository name
  # baseUrl: /your-repo-name
  logoUrl: https://oscz-freiberg.de/wp-content/webp-express/webp-images/uploads/2023/10/logo-ohne-background.png.webp
  favicon: https://oscz-freiberg.de/wp-content/uploads/2023/09/csm_HAUPTLOGO_OSCZ_bunt_e1dda8efcb_2-transformed-1-150x150.png
  name: InFra-OsCZ
  introTitle: "**InFra-OsCZ**: Status-Meldungen, Updates und Hinweise zu den Online-Diensten der Bildungseinrichtung"
  introMessage: Auf dieser Seite sehen Sie in Echtzeit, welche Dienste der Oberschule Online verfügbar sind. Bei Problemen werden Sie hier zuerst informiert. Mehr auf [der Schulwebsite erklärt](https://oscz-freiberg.de/statusinfra).
  navbar:
    - title: Status
      href: /
    - title: Kontakt
      href: mailto:kontakt@oscz-freiberg.de

i18n:
activeIncidents: Aktive Vorfälle
allSystemsOperational: Alle Systeme operativ
incidentReport: Vorfall #$NUMBER Bericht →
activeIncidentSummary: Geöffnet am $DATE mit $POSTS Beiträgen
incidentTitle: Vorfall $NUMBER Details
incidentDetails: Vorfall-Details
incidentFixed: Behoben
incidentOngoing: Laufend
incidentOpenedAt: Geöffnet am
incidentClosedAt: Geschlossen am
incidentViewOnGitHub: Ansicht und Abonnement auf GitHub
incidentCommentSummary: Gepostet am $DATE von $AUTOR
incidentBack: ← Zurück zu allen Vorfällen
pastIncidents: Vergangene Vorfälle
pastIncidentsResolved: Behoben in $MINUTES Minuten mit $POSTS Beiträgen
liveStatus: Live-Status
overallUptime: "Gesamtbetriebszeit: $UPTIME"
overallUptimeTitle: Gesamtbetriebszeit
averageResponseTime: "Durchschnittliche Antwortzeit: $TIMEms"
averageResponseTimeTitle: Durchschnittliche Antwortzeit
sevelDayResponseTime: 7-Tage-Antwortzeit
responseTimeMs: Antwortzeit (ms)
up: Betriebsbereit
down: Außer Betrieb
degraded: Eingeschränkte Funktionalität
ms: Millisekunden
loading: Lädt
navGitHub: GitHub
footer: Diese Seite ist Open Source: $REPO und wird von Upptime: https://upptime.js.org betrieben.
rateLimitExceededTitle: Anfragebereichsgrenze überschritten
rateLimitExceededIntro: Sie haben die zulässige Anzahl an Anfragen pro Stunde überschritten. Bitte warten Sie, bevor Sie erneut auf diese Website zugreifen können. Alternativ können Sie einen GitHub Personal Access Token hinzufügen, um diese Website weiterhin nutzen zu können.
rateLimitExceededWhatDoesErrorMean: Was bedeutet dieser Fehler?
rateLimitExceededErrorMeaning: Diese Website nutzt die GitHub API, um Echtzeitdaten über den Status unserer Websites abzurufen. Standardmäßig erlaubt GitHub jeder IP-Adresse 60 Anfragen pro Stunde, welche Sie aufgebraucht haben.
rateLimitExceededErrorHowCanFix: Wie kann ich das Problem beheben?
rateLimitExceededErrorFix: Sie können eine weitere Stunde warten, bis das Limit Ihrer IP-Adresse wiederhergestellt wird. Alternativ können Sie Ihren GitHub Personal Access Token hinzufügen, der Ihnen 5.000 zusätzliche Anfragen pro Stunde gewährt.
rateLimitExceededGeneratePAT: Erfahren Sie, wie Sie einen Personal Access Token generieren können.
rateLimitExceededHasSet: Sie haben einen Personal Access Token eingerichtet.
rateLimitExceededRemoveToken: Token entfernen
rateLimitExceededGitHubPAT: GitHub Personal Access Token
rateLimitExceededCopyPastePAT: Kopieren und Einfügen Sie Ihren Token
rateLimitExceededSaveToken: Token speichern
errorTitle: Ein Fehler ist aufgetreten
errorIntro: Beim Versuch, die neuesten Statusdetails abzurufen, ist ein Fehler aufgetreten.
errorText: Sie können es in wenigen Augenblicken erneut versuchen.
errorHome: Zur Startseite gehen
pastScheduledMaintenance: Vergangene geplante Wartungen
scheduledMaintenance: Geplante Wartungen
scheduledMaintenanceSummaryStarted: Gestartet am $DATE für $DURATION Minuten
scheduledMaintenanceSummaryStarts: Startet am $DATE für $DURATION Minuten
startedAt: Gestartet am
startsAt: Startet am
duration: Dauer
durationMin: $DURATION Minuten
incidentCompleted: Abgeschlossen
incidentScheduled: Geplant
duration24H: 24 Std.
duration7D: 7 Tage
duration30D: 30 Tage
duration1Y: 1 Jahr
durationAll: Alle

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
